name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Configure AWS credentials using session token
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Set environment variables for Terraform backend
      - name: Set Environment Variables
        run: |
          echo "TF_BUCKET=terraform-state-kazem-sindy" >> $GITHUB_ENV

      # Terraform Init with backend configuration
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=terraform/state/terraform.tfstate" \
            -backend-config="region=us-east-1"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
