- name: Initialize Terraform
  run: terraform init

- name: Select Workspace
  run: terraform workspace select ${{ inputs.workspace }}

- name: Plan Destruction
  run: terraform plan -destroy

- name: Destroy Terraform Resources
  run: terraform destroy -auto-approve
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
